### PR TITLE
#169 - Refactor TgzRelativePath by adding processor

### LINKED ISSUE #169: Incorrect path in TgzRelativePath
After the NPM uploads a package without scope, the package cannot be downloaded based on the tarball.                                   

Code to reproduce:                                                                                                                                        
```                                                                                                                                               
 new TgzRelativePath(                                                                                                                   
            "http://some.host/artifactory/api/npm/npm-tmptest/zlComponent/1.0.1/zlComponent-1.0.1.tgz")       
            .relative()                                                                                                                 
```
                                                                                                                                     
expected: `zlComponent/1.0.1/zlComponent-1.0.1.tgz`
result: `1.0.1/zlComponent-1.0.1.tgz`

### PR DESCRIPTION
**Pull request by genryxy**
Closes #169 
Added opportunity to process obtained relative path by replacing hyphen with version.
Also, made a class `public` because it was made `private` [in this PR](https://github.com/artipie/npm-adapter/commit/f8048a045767967f6bc62cbee5ad9ddf854f517c#diff-863dbc50bf7a87588099c39de9f78b06166ef4b7599959019cbd69525a0fd67b), but some of our users use `TgzRelativePath `

### CODE REVIEW

File: src/main/java/com/artipie/npm/TgzRelativePath.java [hunk 1]
```diff
@@ -24,61 +28,104 @@
...
+
+    /**
+     * Extract the relative path.
+     * @param process Is it necessary to process path value by replacing
+     *  `/-/` with `/version/`. It could be required for some cases.
+     *  See <a href="https://www.jfrog.com/confluence/display/BT/npm+Repositories">
+     *  Deploying with cURL</a> section.
+     * @return The relative path.
+     */
+    public String relative(final boolean process) {
```
Comment (olenagerasimova) [inline src/main/java/com/artipie/npm/TgzRelativePath.java:52]: @genryxy I'd suggest to rename `process` into `replace`

File: src/main/java/com/artipie/npm/TgzRelativePath.java [hunk 2]
```diff
@@ -97,15 +146,59 @@ public String relative() {
...
+
+    /**
+     * Contains matched values which were obtained from regex.
+     * @since 0.9
+     */
+    private static final class Matched {
+        /**
+         * First group from matcher.
+         */
+        private final String cfirstgroup;
```
Comment (olenagerasimova) [inline src/main/java/com/artipie/npm/TgzRelativePath.java:171]: @genryxy I'd suggest to rename this field into `fgroup` (the`f` is from group)

**Review by olenagerasimova — APPROVED** [review]
@genryxy thanks, just two minor naming comments, take a look please

**Comment by 0crat** [comment]
Job audit: `ARC` didn't merge or close PR, performer @olenagerasimova[/z](https://www.0crat.com/u/olenagerasimova)[/z](https://www.0crat.com/u/olenagerasimova) didn't make CR comments
